### ISSUE TITLE
Error by  verify token with certificate

### ISSUE THREAD

**Issue by linqingfeng** [FarmBot/mqtt-gateway#3]
Hi,

We just use the latest version of the deployment, start mqtt, the following error:

Server online
Downloaded certificate from http://localhost:3000/api/public_key
Will fetch certificate...
Did fetch certifiacte. Will verify token with certificate.
Failed to authorize device_4
invalid signature
{ [JsonWebTokenError: invalid signature] name: 'JsonWebTokenError', message: 'invalid signature' }

How to solve?
thank you very much!

**Comment by RickCarlino** [comment]
@linqingfeng Did you recently reset your API server? This is an authorization failure. Here is how authorization works in MQTT:

 1. MQTT server starts
 2. MQTT server downloads a trusted public signing key from `/api/public_key`
 3. MQTT server is now ready to check credentials.
 4. When a user tries to log in (with a token), the MQTT server uses the `public_key` from step 2 to verify that the token came from the API and is not a fake.

This error could be caused by:

 1. logging in with an old account.
 2. deleting a key file (`jwt.development.pem`).
 3. Reseting the server but not resetting the MQTT broker.

I would imagine that if you were to create a new account, the problem would go away. I am still curious as to why this happened.

Which version of the MQTT server / API server are you running? Please let me know by typing `git log --pretty=format:"%h" -1`

Did you recently reset your API server?

Thanks for your help! I would be very interested to isolate the cause of this issue.

**Comment by RickCarlino** [comment]
Oh, one more thing, @linqingfeng : The MQTT client is undergoing heavy work today. Please be aware of that if you are going to use the latest version on the `master` branch.

**Comment by RickCarlino** [comment]
@linqingfeng I just fixed some issues on the MQTT server just now.

These issues were only related to HTTPS and SSL. Are you trying to run SSL on your server?

**Comment by linqingfeng** [comment]
@RickCarlino We run git log --pretty=format:"%h" -1,the results are as follows:
farmbot-web-app：350d7bd
mqtt-gateway：8f596cc

As you said, a new user, it will not report this error.
Thank you very much \ (^ o ^) / ~
